### PR TITLE
refactor goal model

### PR DESCRIPTION
**Pull request by ritosilva**

### CODE REVIEW

**Comment by xbitres** [comment]
Following tests are failing:
RestDesignInterfaceTest.tearDown:-1->advised$tearDown:71 » VersionNotAvailable
  ImportTwoEntitiesTest.importTwoEntitiesTestFromFile:34->lambda$importTwoEntitiesTestFromFile$1:34 » VersionNotAvailable
  SpecXmlExportTest.export:23 » VersionNotAvailable Couldn't reload attribute 'p...
  SpecXmlImportTest>TeardownRollbackTest.setUp:21->populate4Test:30->lambda$populate4Test$1:29 » VersionNotAvailable
  SpecXmlImportTest>TeardownRollbackTest.setUp:21->populate4Test:30->lambda$populate4Test$1:29 » VersionNotAvailable
  SpecXmlImportTest>TeardownRollbackTest.setUp:21->populate4Test:30->lambda$populate4Test$1:29 » VersionNotAvailable

**Comment by xbitres** [comment]
Bug: Specifications created during tests remain in the database during normal execution of the engine

**Comment by ritosilva** [comment]
I guess that it is necessary to drop and create a new database, because de DML model was changed

And install this plugin in Chrome, https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en, because of CORS

**Comment by xbitres** [comment]
The errors presented above were due to previous version of database. Everything is up and running

**Pull request merged**
